---
paths:
  build_file: /tmp/root.fs
  build: /tmp/build_file_mount
  package_list: ./packages
  overlay: ./overlay
  scripts: ./scripts
  output: /tmp/root.fs.sfs
org: akerl
fs:
  size: 4096
  type: btrfs
  flags: -f
keys:
  - https://raw.githubusercontent.com/akerl/keys/master/strong/ender-ed25519
  - https://raw.githubusercontent.com/akerl/keys/master/strong/mazer-ed25519
tarballs:
  - package: s6
    version: 2.1.1.0-10
  - package: execline
    version: 2.0.2.1-10
  - package: s6-linux-utils
    version: 2.0.0.1-9
  - package: docker
    org: dock0
    version: 1.5.0-9
cleanup:
  users:
    - ftp
    - http
  paths:
    - srv/ftp
    - srv/http
    - etc/systemd/system/getty.target.wants/getty@tty1.service
    - etc/skel/.bashrc
    - etc/skel/.bash_logout
    - etc/skel/.bash_profile
    - etc/pacman.d/gnupg/pubring.gpg~
  packages:
    - systemd
...
