---
paths:
  build_file: /tmp/root.fs
  build: /tmp/build_file_mount
  package_list: ./packages
  overlay: ./overlay
  scripts: ./scripts
  output: /tmp/root.fs.sfs
org: akerl
fs:
  size: 4096
keys:
  url: https://id-ed25519.pub/groups/strong.txt
cleanup:
  users:
    - ftp
    - http
  paths:
    - srv/ftp
    - srv/http
    - etc/skel/.bashrc
    - etc/skel/.bash_logout
    - etc/skel/.bash_profile
    - etc/pacman.d/gnupg/pubring.gpg~
...
