---
paths:
  build_file: /tmp/root.fs
  build: /tmp/build_file_mount
  package_list: ./packages
  overlay: ./overlay
  scripts: ./scripts
  output: /tmp/root.fs.sfs
org: akerl
fs:
  size: 4096
  type: btrfs
  flags: -f
keys:
  repo: git://github.com/akerl/keys
  group: strong
cleanup:
  users:
    - ftp
    - http
  paths:
    - srv/ftp
    - srv/http
    - etc/systemd/system/getty.target.wants/getty@tty1.service
    - etc/skel/.bashrc
    - etc/skel/.bash_logout
    - etc/skel/.bash_profile
    - etc/pacman.d/gnupg/pubring.gpg~
...
