#!/usr/bin/env bash

docker run \
    --rm -t -i \
    --privileged \
    -v $SSH_AUTH_SOCK:/auth.sock \
    -e SSH_AUTH_SOCK=/auth.sock \
    -v $(pwd):/opt/vm_root \
    -v ~/.gitconfig:/etc/gitconfig \
    vm_root $1
