version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/rootfs
    environment:
      - PKGFORGE_STATEFILE: '/tmp/pkgforge'
    steps:
      - checkout:
      - run:
          command: git submodule update --init
      - run:
          command: git fetch --tags origin
      - run:
          command: make
      - run:
          command: cp -r pkg/* $CIRCLE_ARTIFACTS/
  deploy:
    machine:
      enabled: true
    working_directory: ~/rootfs
    environment:
      - PKGFORGE_STATEFILE: '/tmp/pkgforge'
    steps:
      - run:
          command: make release
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            tags:
              only: /.*/
